### POST request to create a short url
POST http://localhost:3001/
Content-Type: application/json

{
  "url": "https://www.tutorialspoint.com/postgresql/postgresql_alter_database.htm"
}

### POST request to create a short url from invalid url
POST http://localhost:3001/
Content-Type: application/json

{
  "url": "invalidurl.com"
}

### GET request to get the original url from a short url
GET http://localhost:3001/I7KfL44Q

### GET request to get the original url from random value
GET http://localhost:3001/12312312